# Generated by roxytest: Do not edit by hand!

# File R/math.r: @tests

test_that("Function prob_to_odds() @ L17", {
  expect_equal(prob_to_odds(0.25), 1/3)
  expect_equal(prob_to_odds(0.75), 3)
  expect_equal(prob_to_odds(1), Inf)
  expect_equal(prob_to_odds(0), 0)
})


test_that("Function odds_to_prob() @ L34", {
  expect_equal(odds_to_prob(1/3), 0.25)
  expect_equal(odds_to_prob(3), 0.75)
  expect_equal(odds_to_prob(Inf), 1)
  expect_equal(odds_to_prob(0), 0)
})

