# Generated by roxytest: Do not edit by hand!

# File R/formatting.r: @tests

test_that("Function quoted_list_string() @ L7", {
  expect_equal(
   quoted_list_string(c('a','b','c')),
   '"a", "b", "c"'
  )
})


test_that("Function get_indefinite_article() @ L22", {
  expect_equal(
   get_indefinite_article('fruit'),
   'a'
  )
  
  expect_equal(
   get_indefinite_article('apple'),
   'an'
  )
})


test_that("Function create_param_formatter() @ L36", {
  expect_equal(
   create_param_formatter(digits = 4)(0.1234567),
   "0.1235"
  )
})

